name: Fazendo deploy da aplicaÃ§Ã£o no s3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazendo checkout do cÃ³digo ğŸ¥¹
        uses: actions/checkout@v2

      - name: Configurando Node.js âœ¨
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Instalando as dependÃªncias ğŸ™
        run: npm install

      - name: Fazendo build da aplicaÃ§Ã£o ğŸ”¥
        run: npm run build 

      - name: Deploy no S3 ğŸ‰
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync dist/ s3://gabarito-angular
